[tools]
python = "latest"
bat = "latest"
delta = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
pandoc = "latest"
rg = "latest"
shellcheck = "latest"
shfmt = "latest"
cookiecutter = "latest"
watchexec = "latest"
