##### NAVIGATION #####

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

##### SCROLLBACK / MOUSE #####
set -g history-limit 10000
set -g mouse on
set -g display-panes-time 4000


##### TERMINAL / FEATURES #####
# Good default for modern terminals including WSL2
set -g default-terminal "tmux-256color"

# Truecolor + focus tracking
set -as terminal-overrides ",*:Tc"
set -as terminal-features  ",xterm-256color:RGB,focus"

# Enable focus events
set -g focus-events on


##### TIMING #####
# Instant escape (good for vim)
set -g escape-time 0


##### WINDOWS / PANES #####
set-option -g  base-index 1
setw       -g  pane-base-index 1
set-option -g  renumber-windows on

# Split shortcuts
bind t split-window -f -l 15       # small pane below
bind T split-window -h -f -p 35    # small pane right


##### COPY MODE #####
set-window-option -g mode-keys vi

# Enter copy mode
bind Escape copy-mode
bind C-[    copy-mode

# Copy text with visual selection → xclip
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Paste
bind p paste-buffer


##### STATUS BAR #####
set -g status-position top
set -g status-justify left

# Style
set -g status-style                  'fg=red'
set -g status-bg                     cyan
set -g window-status-style           'fg=red bg=black'
set -g window-status-current-style   'fg=black bg=red'
set -g window-status-format          ' #I #[fg=white]#W #[fg=yellow]#F '
set -g window-status-current-format  ' #I #W #F '
set -g window-status-bell-style      'fg=yellow bg=red bold'

# Status left/right
set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50


##### MISC #####
# Reload tmux.conf
bind r source-file ~/.tmux.conf

# Clock mode colours
setw -g clock-mode-colour yellow

# Copy mode style
setw -g mode-style 'fg=black bg=red bold'
