# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[❯](fg:yellow)[❯](fg:red)[❯](fg:green)"
error_symbol = "[❯](fg:red)[❯](fg:red)[❯](fg:red)"

# [git_status]
# disabled = true

[git_commit]
only_detached = false
